require('dotenv').config();
const express = require('express'); const mongoose = require('mongoose'); const bcrypt = require('bcryptjs'); const crypto = require('crypto');
const helmet = require('helmet'); const cors = require('cors'); const compression = require('compression'); const rateLimit = require('express-rate-limit'); const mongoSanitize = require('express-mongo-sanitize'); const multer = require('multer'); const { z } = require('zod');
const { Terminal, User, Audit, ImportRun, AgentJob } = require('./models'); const { sign, auth, permit, audit } = require('./security'); const { importWorkbook } = require('./importer'); const { uploadBuffer, deleteFile } = require('./cloudinary');
if (!process.env.JWT_SECRET || process.env.JWT_SECRET.length < 32) { console.error('JWT_SECRET must contain at least 32 characters'); if (require.main === module) process.exit(1); }
const app = express(); app.set('trust proxy', 1); app.use(helmet()); app.use(compression()); app.use(cors({ origin: process.env.CLIENT_ORIGIN?.split(',') || false })); app.use(express.json({ limit: '1mb' })); app.use(mongoSanitize());
app.use('/api/auth', rateLimit({ windowMs: 15*60*1000, limit: 20, standardHeaders: true, legacyHeaders: false }));
app.get('/api/health', async (req, res) => { try { const dbState = mongoose.connection.readyState; const states = {0:'disconnected',1:'connected',2:'connecting',3:'disconnecting'}; res.json({ ok: true, db: states[dbState]||dbState, jwt: !!process.env.JWT_SECRET && process.env.JWT_SECRET.length >= 32, mongo_uri_set: !!process.env.MONGODB_URI, node: process.version }); } catch(e) { res.status(500).json({ ok: false, error: e.message }); } });
const agentPhotoUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1},fileFilter:(req,file,cb)=>cb(null,['image/jpeg','image/png','image/webp'].includes(file.mimetype))});
app.post('/api/auth/login', async (req,res,next)=>{ try { const body=z.object({email:z.string().email(),password:z.string().min(8)}).parse(req.body); const user=await User.findOne({email:body.email.toLowerCase()}); if(!user?.active || !await bcrypt.compare(body.password,user.passwordHash)) return res.status(401).json({message:'Invalid credentials'}); user.lastLoginAt=new Date(); await user.save(); res.json({token:sign(user),user:{id:user.id,name:user.name,email:user.email,role:user.role}}); } catch(e){next(e)} });
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.get('/api/users/agents',auth,permit('admin','manager'),async(req,res,next)=>{try{const agents=await User.find({role:'agent',active:true}).select('name email phoneNumber profilePicture').sort({name:1}).lean();const workloads=await AgentJob.aggregate([{$match:{status:{$nin:['approved','cancelled']}}},{$group:{_id:'$agent',openJobs:{$sum:1}}}]);const counts=new Map(workloads.map(w=>[String(w._id),w.openJobs]));res.json(agents.map(a=>({...a,available:true,openJobs:counts.get(String(a._id))||0})));}catch(e){next(e)}});
app.post('/api/users/agents',auth,permit('admin'),agentPhotoUpload.single('picture'),async(req,res,next)=>{try{const b=z.object({name:z.string().min(2).max(100),email:z.string().email(),phoneNumber:z.string().min(7).max(25).regex(/^[+0-9()\-\s]+$/),password:z.string().min(8)}).parse(req.body);if(!req.file)return res.status(400).json({message:'Agent profile picture is required (JPG, PNG or WebP)'});if(await User.exists({email:b.email.toLowerCase()}))return res.status(409).json({message:'Email already exists'});const uploaded=await uploadBuffer(req.file.buffer,{folder:'atm-command-center/agents',resource_type:'image',public_id:`agent_${crypto.randomUUID()}`,overwrite:false});const user=await User.create({name:b.name,email:b.email.toLowerCase(),phoneNumber:b.phoneNumber,passwordHash:await bcrypt.hash(b.password,12),profilePicture:{storedName:uploaded.publicId,mimeType:req.file.mimetype,originalName:req.file.originalname,size:req.file.size,url:uploaded.secureUrl},role:'agent'});await audit(req,'AGENT_CREATED','User',user.id,{email:user.email,phoneNumber:user.phoneNumber});res.status(201).json({id:user.id,name:user.name,email:user.email,phoneNumber:user.phoneNumber,role:user.role});}catch(e){next(e)}});
app.get('/api/users/agents/:id/picture',auth,async(req,res,next)=>{try{const agent=await User.findOne({_id:req.params.id,role:'agent'}).select('profilePicture');if(!agent?.profilePicture?.url)return res.status(404).end();res.redirect(agent.profilePicture.url);}catch(e){next(e)}});
app.get('/api/dashboard',auth,async(req,res,next)=>{try{const [total,active,inventory,alerts,setupRequired,cities]=await Promise.all([Terminal.countDocuments(),Terminal.countDocuments({'official.status':/^active$/i}),Terminal.countDocuments({'official.sourcePresent':false}),Terminal.countDocuments({'alert.enabled':true,$expr:{$lte:['$official.cashBalance','$alert.threshold']}}),Terminal.countDocuments({setupRequired:true}),Terminal.aggregate([{$group:{_id:'$current.city',count:{$sum:1},payments:{$sum:'$current.paymentAmount'}}},{$sort:{count:-1}},{$limit:8}])]);res.json({total,active,inventory,alerts,setupRequired,cities});}catch(e){next(e)}});
app.get('/api/notifications',auth,async(req,res,next)=>{try{const [setup,lowCash,missing,latestImport]=await Promise.all([Terminal.find({setupRequired:true}).select('terminalId official.status official.name official.address official.city official.locationArea official.cashBalance official.lastCommunication official.lastWithdrawalAt setupReason createdAt').sort({createdAt:-1}).limit(200),Terminal.find({'alert.enabled':true,$expr:{$lte:['$official.cashBalance','$alert.threshold']}}).select('terminalId official.name official.address official.city official.cashBalance alert.threshold').sort({'official.cashBalance':1}).limit(200),Terminal.find({'official.sourcePresent':false}).select('terminalId official.name official.address official.city official.lastSyncedAt').sort({'official.lastSyncedAt':-1}).limit(100),ImportRun.findOne().sort({createdAt:-1}).select('fileName changes totals createdAt').lean()]);const recentChanges=latestImport?.changes||[];res.json({setup,lowCash,missing,recentChanges,latestImport:latestImport?{fileName:latestImport.fileName,createdAt:latestImport.createdAt,totals:latestImport.totals}:null,total:setup.length+lowCash.length+missing.length+recentChanges.length});}catch(e){next(e)}});
app.get('/api/terminals',auth,async(req,res,next)=>{try{const page=Math.max(1,+req.query.page||1),limit=Math.min(100,Math.max(1,+req.query.limit||25));const q={};if(req.query.search){const s=String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');q.$or=[{terminalId:new RegExp(s,'i')},{'current.businessName':new RegExp(s,'i')},{'current.city':new RegExp(s,'i')},{'current.address':new RegExp(s,'i')}];}if(req.query.status)q['official.status']=req.query.status;if(req.query.city)q['current.city']=new RegExp(`^${String(req.query.city).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`,'i');const [items,total]=await Promise.all([Terminal.find(q).sort({terminalId:1}).skip((page-1)*limit).limit(limit),Terminal.countDocuments(q)]);res.json({items,total,page,pages:Math.ceil(total/limit)});}catch(e){next(e)}});
app.get('/api/terminals/:id',auth,async(req,res,next)=>{try{const item=await Terminal.findOne({terminalId:req.params.id.toUpperCase()}).populate('assignmentHistory.assignedBy','name email');if(!item)return res.status(404).json({message:'Terminal not found'});res.json(item);}catch(e){next(e)}});
app.patch('/api/terminals/:id/status',auth,permit('admin','manager'),async(req,res,next)=>{try{const {status}=z.object({status:z.enum(['Active','Inactive'])}).parse(req.body);const t=await Terminal.findOneAndUpdate({terminalId:req.params.id.toUpperCase()},{$set:{'official.status':status}},{new:true});if(!t)return res.status(404).json({message:'Terminal not found'});await audit(req,'TERMINAL_STATUS_CHANGED','Terminal',t.id,{terminalId:t.terminalId,status});res.json(t);}catch(e){next(e)}});
app.post('/api/terminals/:id/assign',auth,permit('admin','manager'),async(req,res,next)=>{try{const b=z.object({businessName:z.string().min(2).max(150),address:z.string().min(3).max(250),city:z.string().min(2).max(100),wishAmount:z.number().nonnegative(),paymentAmount:z.number().nonnegative().optional(),note:z.string().max(1000).optional(),agentId:z.string().optional(),cashToLoad:z.number().nonnegative().optional(),dueAt:z.string().optional()}).parse(req.body);const t=await Terminal.findOne({terminalId:req.params.id.toUpperCase()});if(!t)return res.status(404).json({message:'Terminal not found'});let agent;if(b.agentId){agent=await User.findOne({_id:b.agentId,role:'agent',active:true});if(!agent)return res.status(400).json({message:'Selected agent is unavailable'});if(b.cashToLoad==null||!b.dueAt)return res.status(400).json({message:'Cash to load and due time are required when assigning an agent'});}const now=new Date();const last=t.assignmentHistory.at(-1);if(last&&!last.endedAt)last.endedAt=now;t.assignmentHistory.push({businessName:b.businessName,address:b.address,city:b.city,paymentAmount:b.paymentAmount??b.wishAmount,note:b.note,assignedAt:now,assignedBy:req.user._id});t.official.tempName=b.businessName;t.official.wishAmount=b.wishAmount;t.current={businessName:b.businessName,address:b.address,city:b.city,paymentAmount:b.paymentAmount??b.wishAmount,assignedAt:now};t.alert={enabled:true,threshold:b.wishAmount};t.setupRequired=false;t.setupReason=undefined;await t.save();let job=null;if(agent)job=await AgentJob.create({terminal:t._id,terminalId:t.terminalId,agent:agent._id,assignedBy:req.user._id,businessName:b.businessName,address:b.address,city:b.city,wishAmount:b.wishAmount,cashToLoad:b.cashToLoad,dueAt:new Date(b.dueAt),events:[{status:'assigned',note:b.note,createdBy:req.user._id}]});await audit(req,'TERMINAL_ASSIGNED','Terminal',t.id,{terminalId:t.terminalId,to:b.businessName,agent:agent?.email,cashToLoad:b.cashToLoad,wishAmount:b.wishAmount,jobId:job?.id});res.json({terminal:t,job});}catch(e){next(e)}});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,/\.(xlsx|xls)$/i.test(file.originalname))});
const proofUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024,files:4},fileFilter:(req,file,cb)=>cb(null,['image/jpeg','image/png','image/webp','application/pdf'].includes(file.mimetype))});
app.post('/api/imports',auth,permit('admin'),upload.single('file'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({message:'Excel file required'});const result=await importWorkbook(req.file.buffer,req.file.originalname,req.user._id);await audit(req,'OFFICIAL_IMPORT','ImportRun',result.runId,result);res.status(201).json(result);}catch(e){next(e)}});
app.get('/api/jobs',auth,async(req,res,next)=>{try{const q=req.user.role==='agent'?{agent:req.user._id}:{};if(req.query.status)q.status=req.query.status;if(req.query.search){const rx=new RegExp(String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');q.$or=[{terminalId:rx},{businessName:rx},{city:rx}];}const items=await AgentJob.find(q).sort({dueAt:1,createdAt:-1}).limit(1000).populate('agent','name email').populate('assignedBy','name email').populate('events.createdBy','name email');res.json(items);}catch(e){next(e)}});
app.get('/api/jobs/active-terminal/:terminalId',auth,async(req,res,next)=>{try{const job=await AgentJob.findOne({terminalId:req.params.terminalId.toUpperCase(),status:{$nin:['approved','cancelled']}}).populate('agent','name email').select('terminalId agent status dueAt businessName');res.json({busy:Boolean(job),job});}catch(e){next(e)}});
app.get('/api/location-areas',auth,async(req,res,next)=>{try{const areas=await Terminal.aggregate([{$match:{'official.locationArea':{$nin:[null,'']},'official.sourcePresent':true}},{$group:{_id:'$official.locationArea',terminals:{$sum:1},cities:{$addToSet:{$ifNull:['$official.city','$current.city']}}}},{$sort:{_id:1}}]);res.json(areas.map(a=>({name:a._id,terminals:a.terminals,cities:a.cities.filter(Boolean)})));}catch(e){next(e)}});
app.get('/api/location-areas/:area/terminals',auth,async(req,res,next)=>{try{const area=String(req.params.area);const terminals=await Terminal.find({'official.locationArea':area,'official.sourcePresent':true}).select('terminalId official.name official.locationArea official.wishAmount official.cashBalance official.city current.businessName current.address current.city').sort({'official.city':1,terminalId:1}).lean();const active=await AgentJob.find({terminalId:{$in:terminals.map(t=>t.terminalId)},status:{$nin:['approved','cancelled']}}).select('terminalId agent status').populate('agent','name').lean();const jobs=new Map(active.map(j=>[j.terminalId,j]));res.json(terminals.map(t=>({...t,current:{...t.current,city:t.current?.city||t.official?.city||''},requiredCash:Math.max(0,(t.official?.wishAmount||0)-(t.official?.cashBalance||0)),activeJob:jobs.get(t.terminalId)||null})));}catch(e){next(e)}});
app.post('/api/jobs/dispatch',auth,permit('admin','manager'),async(req,res,next)=>{try{const b=z.object({terminalId:z.string().min(2),agentId:z.string().min(2),cashToLoad:z.number().nonnegative(),dueAt:z.string().min(1),note:z.string().max(2000).optional()}).parse(req.body);const [terminal,agent]=await Promise.all([Terminal.findOne({terminalId:b.terminalId.toUpperCase()}),User.findOne({_id:b.agentId,role:'agent',active:true})]);if(!terminal)return res.status(404).json({message:'Terminal not found'});if(!agent)return res.status(400).json({message:'Selected agent is unavailable'});const terminalJob=await AgentJob.findOne({terminalId:terminal.terminalId,status:{$nin:['approved','cancelled']}}).populate('agent','name');if(terminalJob)return res.status(409).json({message:`${terminal.terminalId} is already assigned to ${terminalJob.agent?.name||'an agent'}. Complete and approve that job before another dispatch.`});const job=await AgentJob.create({terminal:terminal._id,terminalId:terminal.terminalId,agent:agent._id,assignedBy:req.user._id,businessName:terminal.current?.businessName||terminal.official?.tempName||terminal.original?.businessName,address:terminal.current?.address||terminal.original?.address,city:terminal.current?.city||terminal.original?.city,wishAmount:terminal.official?.wishAmount||terminal.alert?.threshold||0,cashToLoad:b.cashToLoad,dueAt:new Date(b.dueAt),events:[{status:'assigned',note:b.note,createdBy:req.user._id}]});await audit(req,'DAILY_AGENT_DISPATCHED','AgentJob',job.id,{terminalId:terminal.terminalId,agent:agent.email,cashToLoad:b.cashToLoad,dueAt:b.dueAt});res.status(201).json(await job.populate('agent','name email'));}catch(e){next(e)}});
app.post('/api/jobs/dispatch-area',auth,permit('admin','manager'),async(req,res,next)=>{try{const b=z.object({locationArea:z.string().min(1),agentId:z.string().min(2),dueAt:z.string().min(1),note:z.string().max(2000).optional(),terminalIds:z.array(z.string()).min(1),cashOverrides:z.record(z.string(),z.number().nonnegative()).optional()}).parse(req.body);const agent=await User.findOne({_id:b.agentId,role:'agent',active:true});if(!agent)return res.status(400).json({message:'Selected agent is unavailable'});const terminals=await Terminal.find({terminalId:{$in:b.terminalIds.map(id=>id.toUpperCase())},'official.locationArea':b.locationArea,'official.sourcePresent':true});const locked=await AgentJob.distinct('terminalId',{terminalId:{$in:terminals.map(t=>t.terminalId)},status:{$nin:['approved','cancelled']}});const lockedSet=new Set(locked);const eligible=terminals.filter(t=>!lockedSet.has(t.terminalId));if(!eligible.length)return res.status(409).json({message:'All selected ATMs already have active jobs'});const batchId=crypto.randomUUID();const jobs=await AgentJob.insertMany(eligible.map(t=>{const defaultLoad=Math.max(0,(t.official?.wishAmount||0)-(t.official?.cashBalance||0));const cashToLoad=b.cashOverrides?.[t.terminalId]??defaultLoad;return{batchId,locationArea:b.locationArea,terminal:t._id,terminalId:t.terminalId,agent:agent._id,assignedBy:req.user._id,businessName:t.current?.businessName||t.official?.tempName||t.original?.businessName,address:t.current?.address||t.original?.address,city:t.current?.city||t.original?.city,wishAmount:t.official?.wishAmount||0,cashToLoad,dueAt:new Date(b.dueAt),events:[{status:'assigned',note:`Area route: ${b.locationArea}${b.note?` — ${b.note}`:''}`,createdBy:req.user._id}]}}));await audit(req,'AREA_ROUTE_DISPATCHED','AgentJob',batchId,{locationArea:b.locationArea,agent:agent.email,assigned:jobs.length,skippedLocked:locked.length,terminalIds:jobs.map(j=>j.terminalId)});res.status(201).json({batchId,assigned:jobs.length,skippedLocked:locked.length,totalCash:jobs.reduce((s,j)=>s+j.cashToLoad,0)});}catch(e){next(e)}});
app.post('/api/jobs/:id/events',auth,proofUpload.array('proofs',4),async(req,res,next)=>{try{const job=await AgentJob.findById(req.params.id);if(!job)return res.status(404).json({message:'Job not found'});const isAgent=req.user.role==='agent'&&String(job.agent)===String(req.user._id);if(!isAgent&&!['admin','manager'].includes(req.user.role))return res.status(403).json({message:'This job is not assigned to you'});const b=z.object({status:z.enum(['accepted','travelling','cash_loaded','issue_reported']),note:z.string().max(2000).optional(),cashLoaded:z.coerce.number().nonnegative().optional()}).parse(req.body);if(b.status==='cash_loaded'&&(b.cashLoaded==null||!req.files?.length))return res.status(400).json({message:'Cash amount and at least one proof file are required'});if(b.status==='issue_reported'&&!b.note)return res.status(400).json({message:'Please describe the issue'});const proofFiles=[];for(const file of req.files||[]){const isPdf=file.mimetype==='application/pdf';const uploaded=await uploadBuffer(file.buffer,{folder:'atm-command-center/proofs',resource_type:isPdf?'raw':'image',public_id:`proof_${crypto.randomUUID()}`,overwrite:false});proofFiles.push({originalName:file.originalname,storedName:uploaded.publicId,mimeType:file.mimetype,size:file.size,url:uploaded.secureUrl});}job.status=b.status;job.events.push({status:b.status,note:b.note,cashLoaded:b.cashLoaded,proofFiles,createdBy:req.user._id});await job.save();await audit(req,'AGENT_JOB_UPDATED','AgentJob',job.id,{terminalId:job.terminalId,status:b.status,cashLoaded:b.cashLoaded});res.json(job);}catch(e){next(e)}});
app.post('/api/jobs/:id/approve',auth,permit('admin','manager'),async(req,res,next)=>{try{const job=await AgentJob.findById(req.params.id);if(!job)return res.status(404).json({message:'Job not found'});if(job.status!=='cash_loaded')return res.status(400).json({message:'Only a cash-loaded job can be approved'});job.status='approved';job.approvedAt=new Date();job.approvedBy=req.user._id;job.events.push({status:'approved',note:req.body?.note,createdBy:req.user._id});await job.save();await Terminal.updateOne({_id:job.terminal},{$set:{'official.cashBalance':job.events.filter(e=>e.status==='cash_loaded').at(-1)?.cashLoaded??job.cashToLoad}});await audit(req,'AGENT_JOB_APPROVED','AgentJob',job.id,{terminalId:job.terminalId});res.json(job);}catch(e){next(e)}});
app.get('/api/jobs/:id/proofs/:file',auth,async(req,res,next)=>{try{const job=await AgentJob.findById(req.params.id);if(!job)return res.status(404).end();const allowed=req.user.role!=='agent'||String(job.agent)===String(req.user._id);if(!allowed)return res.status(403).end();const proof=job.events.flatMap(e=>e.proofFiles||[]).find(f=>f.storedName===req.params.file||f.url===req.params.file);if(!proof?.url)return res.status(404).end();res.redirect(proof.url);}catch(e){next(e)}});
app.get('/api/imports',auth,async(req,res,next)=>{try{res.json(await ImportRun.find().sort({createdAt:-1}).limit(20).populate('importedBy','name'));}catch(e){next(e)}});app.get('/api/audit',auth,permit('admin'),async(req,res,next)=>{try{res.json(await Audit.find().sort({createdAt:-1}).limit(100).populate('actor','name email'));}catch(e){next(e)}});
app.get('/api/assignment-history',auth,permit('admin'),async(req,res,next)=>{try{const escape=s=>String(s||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const match={};if(req.query.search){const rx=new RegExp(escape(req.query.search),'i');match.$or=[{terminalId:rx},{'assignmentHistory.businessName':rx},{'assignmentHistory.address':rx},{'assignmentHistory.city':rx}];}if(req.query.city)match['assignmentHistory.city']=new RegExp(`^${escape(req.query.city)}$`,'i');if(req.query.from||req.query.to){match['assignmentHistory.assignedAt']={};if(req.query.from)match['assignmentHistory.assignedAt'].$gte=new Date(`${req.query.from}T00:00:00`);if(req.query.to)match['assignmentHistory.assignedAt'].$lte=new Date(`${req.query.to}T23:59:59.999`);}const limit=Math.min(5000,Math.max(1,+req.query.limit||500));const pipeline=[{$unwind:'$assignmentHistory'},{$match:match},{$lookup:{from:'users',localField:'assignmentHistory.assignedBy',foreignField:'_id',as:'assignedUser'}},{$unwind:{path:'$assignedUser',preserveNullAndEmptyArrays:true}},{$project:{_id:0,terminalId:1,originalBusiness:'$original.businessName',originalAddress:'$original.address',businessName:'$assignmentHistory.businessName',address:'$assignmentHistory.address',city:'$assignmentHistory.city',paymentAmount:'$assignmentHistory.paymentAmount',assignedAt:'$assignmentHistory.assignedAt',endedAt:'$assignmentHistory.endedAt',note:'$assignmentHistory.note',assignedBy:'$assignedUser.name',assignedByEmail:'$assignedUser.email'}},{$sort:{assignedAt:-1}},{$limit:limit}];const items=await Terminal.aggregate(pipeline);res.json({items,total:items.length,limited:items.length===limit});}catch(e){next(e)}});
app.use((err,req,res,next)=>{console.error(err);if(err.name==='ZodError')return res.status(400).json({message:'Validation failed',issues:err.issues});res.status(500).json({message:'An unexpected error occurred',...(process.env.NODE_ENV!=='production'?{detail:err.message}:{})});});
async function start(){await mongoose.connect(process.env.MONGODB_URI);const email=process.env.ADMIN_EMAIL?.toLowerCase();if(email&&!await User.exists({email}))await User.create({name:'Administrator',email,passwordHash:await bcrypt.hash(process.env.ADMIN_PASSWORD,12),role:'admin'});app.listen(process.env.PORT||4000,()=>console.log(`API ready on ${process.env.PORT||4000}`));} if(require.main===module)start().catch(e=>{console.error(e);process.exit(1)});

// Vercel serverless handler
async function connectDB() {
  if (mongoose.connection.readyState === 1) return; // already connected
  await mongoose.connect(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 8000 });
  const email = process.env.ADMIN_EMAIL?.toLowerCase();
  if (email && !await User.exists({ email })) {
    await User.create({ name: 'Administrator', email, passwordHash: await bcrypt.hash(process.env.ADMIN_PASSWORD, 12), role: 'admin' });
  }
}

module.exports = async (req, res) => {
  try {
    await connectDB();
  } catch (e) {
    console.error('DB connection failed:', e.message);
    return res.status(500).json({ message: 'Database connection failed', detail: e.message });
  }
  return app(req, res);
};
