import React,{useEffect,useState}from'react';
const req=async(p,o={})=>{const r=await fetch('/api'+p,{...o,headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('token')}`,...o.headers}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Request failed');return d};
export default function DailyDispatch({done}){
  const[terminalId,setTerminalId]=useState(''),[terminal,setTerminal]=useState(),[agents,setAgents]=useState([]),[msg,setMsg]=useState(''),[f,setF]=useState({agentId:'',cashToLoad:0,dueAt:'',note:''});
  const loadAgents=()=>req('/users/agents').then(setAgents);useEffect(()=>{loadAgents()},[]);
  async function find(e){e.preventDefault();try{const[atm,active]=await Promise.all([req('/terminals/'+terminalId),req('/jobs/active-terminal/'+terminalId)]);if(active.busy){setTerminal();return setMsg(`${terminalId} is already assigned to ${active.job?.agent?.name||'an agent'} (${active.job?.status}). Complete and approve that job first.`)}setTerminal(atm);setMsg('ATM is available for a new daily dispatch.')}catch(e){setTerminal();setMsg(e.message)}}
  async function dispatch(e){e.preventDefault();try{await req('/jobs/dispatch',{method:'POST',body:JSON.stringify({...f,terminalId:terminal.terminalId,cashToLoad:+f.cashToLoad})});setMsg('Daily job assigned successfully. This ATM is locked, but the agent can receive other ATM jobs.');setTerminal();setF({agentId:'',cashToLoad:0,dueAt:'',note:''});loadAgents();done?.()}catch(e){setMsg(e.message)}}
  return <div className="daily-dispatch"><section className="dispatch-form"><p className="eyebrow">DAILY CASH OPERATION</p><h2>Assign an ATM job to an agent</h2><p>One ATM can have only one open job. An agent may handle multiple different ATMs.</p><form className="find-terminal" onSubmit={find}><input placeholder="Search Terminal ID" value={terminalId} onChange={e=>setTerminalId(e.target.value.toUpperCase())}/><button>Check ATM</button></form>{terminal&&<div className="terminal-snapshot"><div><small>AVAILABLE TERMINAL</small><b>{terminal.terminalId}</b></div><div><small>CURRENT LOCATION</small><b>{terminal.current?.businessName}</b><span>{terminal.current?.address}</span></div><div><small>WISH AMOUNT</small><b>${(terminal.official?.wishAmount||0).toLocaleString()}</b></div></div>}<form className={!terminal?'locked':''} onSubmit={dispatch}><label>Select agent<select required value={f.agentId} onChange={e=>setF({...f,agentId:e.target.value})}><option value="">Select agent...</option>{agents.map(a=><option key={a._id} value={a._id}>{a.name} — {a.openJobs} open job(s)</option>)}</select><small>All active agents can receive multiple ATM jobs.</small></label><div className="two"><label>Cash given to load<input type="number" min="0" required value={f.cashToLoad} onChange={e=>setF({...f,cashToLoad:e.target.value})}/></label><label>Complete before<input type="datetime-local" required value={f.dueAt} onChange={e=>setF({...f,dueAt:e.target.value})}/></label></div><label>Daily instructions<textarea value={f.note} onChange={e=>setF({...f,note:e.target.value})}/></label><button>Dispatch daily job →</button></form>{msg&&<p className={msg.includes('successfully')||msg.includes('available')?'success':'error'}>{msg}</p>}</section><aside className="agent-availability"><p className="eyebrow">AGENT WORKLOAD</p><h3>Active assignments</h3>{agents.map(a=><div key={a._id}><span className={a.openJobs?'busy':'available'}></span><section><b>{a.name}</b><small>{a.email}</small></section><strong>{a.openJobs} open</strong></div>)}</aside></div>
}
